create database train;
use train;
create table personal(Login_id varchar(50),Pass int,primary key(Login_id,Pass));
create table delhi_to_mumbai(T_name Varchar(100),T_number Varchar(50),Duration Decimal(4,2),primary key(T_number));
create table indore_to_mumbai(T_name Varchar(100),T_number Varchar(50),Duration Decimal(4,2),primary key(T_number));
create table jaipur_to_mumbai(T_name Varchar(100),T_number Varchar(50),Duration Decimal(4,2),primary key(T_number));
create table indore_to_delhi(T_name Varchar(100),T_number Varchar(50),Duration Decimal(4,2),primary key(T_number));
create table ahmedabad_to_delhi(T_name Varchar(100),T_number Varchar(50),Duration Decimal(4,2),primary key(T_number));
create table indore_to_jaipur(T_name Varchar(100),T_number Varchar(50),Duration Decimal(4,2),primary key(T_number));
insert into personal value('namanverma14',156618);
insert into personal value('ashirbadnayak04',532425);
insert into personal value('thrishulreddy00',984654);
select * from personal;
insert into delhi_to_mumbai values('NEWDELHI_MUMBAICENTRAL_RajdhaniExpress','12952',15.40);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_BANDRATERMINUS_Garib_Rath_Express','12910',16.45);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_MUMBAICENTRAL_August_Kranti_Rajdhani_Exppress','12954',16.50);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_MUMBAICSMT_Rajdhani_Express','22222',16.55);
insert into delhi_to_mumbai values('AMRITSAR_MUMBAICENTRAL_Golden_Temple_SF_Mail','12904',19.45);
insert into delhi_to_mumbai values('AMRITSAR_MUMBAICSMT_Express','11058',27.25);
insert into delhi_to_mumbai values('HARIDWAR_BANDRATERMINUS_Express','19020',27.20);
insert into delhi_to_mumbai values('AMRITSAR_KOCHUVELI_SF_Express','12484',18.25);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_TRIVANDRUMCENTRAL_Rajdhani_Express','12432',16.49);
insert into delhi_to_mumbai values('CHANDIGARH_BANDRATERMINUS_SF_Express','22452',21.28);
insert into delhi_to_mumbai values('AMRITSAR_BANDRATERMINUS_Paschim_SF_Express','12926',22.50);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_ERNAKULAM_Mangla_Lakshadweep_SF_Express','12618',23.50);
insert into delhi_to_mumbai values('FIROZPURCANTT_MUMBAICSMT_Punjab_Mail_SF_Express','12138',26.20);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_MADGAON_Rajdhani_Express','22414',16.49); 
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_PUNE_AC_SF_Express','12494',17.37);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_TRIVANDRUMCENTRAL_SF_Express','22634',18.40);
insert into delhi_to_mumbai values('HARIDWAR_MUMBAILTT_AC_SF_Express','12172',22.50);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_ERNAKULAM_SF_Express','22656',19.26);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_ERNAKULAM_Duronto_Express','12284',17.50);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_TRIVANDRUMCENTRAL_SF_Express','22654',19.26);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_PUNE_AC_Duronto_Express','12264',15.29);
insert into delhi_to_mumbai values('NEWDELHI_MUMBAICENTRAL_AC_Duronto_Express','22210',17.40);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_BANDRATERMINUS_Yuva_Express','12248',16.45);
insert into delhi_to_mumbai values('CHANDIGARH_MADGAON_Goa_Sampark_Kranti_Express','12450',18.30);
insert into delhi_to_mumbai values('DELHISARAIROHILLA_BANDRATERMINUS_SF_Express','22950',22.55);
insert into delhi_to_mumbai values('YOGNAGARIRISHIKESH_KOCHUVELI_SF_Express','22660',18.10);
insert into delhi_to_mumbai values('DELHISARAIROHILLA_BANDRATERMINUS_Garib_Rath_Express','12215',22.40);
insert into delhi_to_mumbai values('HARIDWAR_BANDRATERMINUS_SF_Express','22918',18.35);
insert into delhi_to_mumbai values('CHANDIGARH_KOCHUVELI_Kerela_Sampark_Kranti_Express','12218',18.25);
insert into delhi_to_mumbai values('SMVDKATRA_BANDRATERMINUS_Swaraj_SF_Express','12472',18.30);
insert into delhi_to_mumbai values('HAZRATNIZAMUDDIN_BANDRATERMINUS_Sampark_Kranti_Express','12902',16.45);
select * from delhi_to_mumbai order by Duration asc;
insert into indore_to_mumbai values('INDB - LPI HUMSAFAR_Superfast','20916',11.30);
insert into indore_to_mumbai values('INDORE - DAUND EXPRESS_Superfast','22944',12.10);
insert into indore_to_mumbai values('AVANTIKA EXPRESS_Superfast','12962',13.05);
insert into indore_to_mumbai values('INDB - MMCT DURANTO_Duruonto Express','12228',11.20);
insert into indore_to_mumbai values('INDB KCVL EXP_Superfast','20932',12.25);
select * from indore_to_mumbai order by Duration asc;
insert into jaipur_to_mumbai values('JP-BDTS SUMMER SPL_Superfast','09723',19.54);
insert into jaipur_to_mumbai values('AJMER-BANDRA SF SPECIAL_Superfast','09621',18.16);
insert into jaipur_to_mumbai values('AMRAPURA ARAVALI EXP_Superfast','14701',19.43);
insert into jaipur_to_mumbai values('MARU SAGAR EXP_Superfast','12978',17.05);
insert into jaipur_to_mumbai values('JP PUNE EXP_Superfast','12940',15.40);
insert into jaipur_to_mumbai values('JP BDTS SF EXP_Superfast','22934',16.19);
insert into jaipur_to_mumbai values('DEE BDTS GARIBRATH_Superfast','12215',17.01);
insert into jaipur_to_mumbai values('JP MMCT SF EXP_Superfast','12956',16.55);
insert into jaipur_to_mumbai values('JP BDTS EXP_Superfast','12980',15.54);
insert into jaipur_to_mumbai values('HSR MMCT DRNT EXP_Superfast','12240',15.30);
select * from jaipur_to_mumbai order by Duration asc;
insert into indore_to_delhi values('INDB CDG EXPRESS_Mail','19307',17.35);
insert into indore_to_delhi values('MALWA EXPRESS_Superfast','12919',16.00);
insert into indore_to_delhi values('INDB NDLS SF EXP_Superfast','20957',11.45);
insert into indore_to_delhi values('IND NZM EXPRESS_Superfast','12415',13.00);
insert into indore_to_delhi values('IND DDN EXPRESS_Superfast','14317',16.45);
insert into indore_to_delhi values('INDB DEE EXP_Superfast','19337',16.45);
insert into indore_to_delhi values('IND AMRITSAR EXP_Superfast','19325',15.40);
insert into indore_to_delhi values('INBD UHP EXPRESS_Superfast','22941',10.57);
select * from indore_to_mumbai order by Duration asc;
insert into ahmedabad_to_delhi values('SULTANPUR EXPRESS_Superfast','20939',14.59);
insert into ahmedabad_to_delhi values('ADI YNRK EXP_Superfast','19031',17.13);
insert into ahmedabad_to_delhi values('SARVODAYA EXP_Superfast','12473',15.05);
insert into ahmedabad_to_delhi values('HAPA-SVDK EXPRESS_Superfast','12475',15.05);
insert into ahmedabad_to_delhi values('JAM SVDK EXPRESS_Superfast','12477',15.05);
insert into ahmedabad_to_delhi values('GUJARAT SAMPARKRANTI_Superfast','12917',14.20);
insert into ahmedabad_to_delhi values('SWARNA JAYANTI RAJDHANI_Superfast','12957',13.00);
insert into ahmedabad_to_delhi values('BDTS-DEE GARIBRATH_Superfast','12216',15.43);
insert into ahmedabad_to_delhi values('BDTS CDG EXPRESS_Superfast','22451',15.33);
insert into ahmedabad_to_delhi values('AASHRAM EXPRESS_Superfast','12915',13.55);
insert into ahmedabad_to_delhi values('BDTS DEE EXPRESS_Superfast','22949',15.28);
insert into ahmedabad_to_delhi values('ADI VARANASI EXPRESS_Superfast','19407',16.02); 
select * from ahmedabad_to_delhi order by Duration asc;
insert into indore_to_jaipur values('RANTHAMBOR EXP_Superfast','12465',10.35);
insert into indore_to_jaipur values('INDB DEE EXP_Superfast','19337',11.10);
insert into indore_to_jaipur values('INDB-JP EXP_Superfast','12973',9.25);
select * from indore_to_jaipur order by Duration asc;